name: ssmi_sensitivity
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - ipywidgets
  - scipy
  - mpmath
  - six
  - xarray
  - pandas
  - pillow
libraries:
- name: PIL
  version: latest
